CC=gcc
CFLAGS=-Wall -fast
LDFLAGS=-framework OpenGL -framework GLUT -framework CoreFoundation -framework Cocoa

perftest: perftest.o perftest_d3d9.o perftest_ogl.o perftest_mac.o

clean: 
	rm -f perftest *.o
